// Vendor pattern recognition rules
// Maps vendor CLI syntax to semantic security parameters

export const vendorPatterns = {
  'Cisco IOS': {
    identifier: [
      /^hostname\s/m,
      /^version\s+\d+\./m,
      /^ip\s+ssh/m,
      /^interface\s+(GigabitEthernet|FastEthernet|Loopback|Vlan)/m,
      /^line\s+(vty|con|aux)/m,
      /^router\s+(ospf|eigrp|bgp|rip)/m,
      /^enable\s+(secret|password)/m,
      /^aaa\s+new-model/m,
    ],
    patterns: [
      { regex: /ip\s+ssh\s+version\s+(\d+)/i, semantic: 'ssh_version', extract: (m) => parseInt(m[1]) },
      { regex: /ip\s+ssh\b/i, semantic: 'ssh_enabled', extract: () => true },
      { regex: /transport\s+input\s+ssh/i, semantic: 'ssh_enabled', extract: () => true },
      { regex: /transport\s+input\s+telnet/i, semantic: 'telnet_enabled', extract: () => true },
      { regex: /^service\s+telnet/m, semantic: 'telnet_enabled', extract: () => true },
      { regex: /^no\s+service\s+telnet/m, semantic: 'telnet_enabled', extract: () => false },
      { regex: /transport\s+input\s+none/i, semantic: 'telnet_enabled', extract: () => false },
      { regex: /^no\s+ip\s+http\s+server$/m, semantic: 'http_management', extract: () => false },
      { regex: /^ip\s+http\s+server$/m, semantic: 'http_management', extract: () => true },
      { regex: /ip\s+http\s+secure-server/i, semantic: 'https_management', extract: () => true },
      { regex: /access-class\s+\d+\s+in/i, semantic: 'mgmt_acl', extract: () => true },
      { regex: /exec-timeout\s+(\d+)\s+(\d+)/i, semantic: 'session_timeout', extract: (m) => parseInt(m[1]) * 60 + parseInt(m[2]) },
      { regex: /aaa\s+new-model/i, semantic: 'aaa_enabled', extract: () => true },
      { regex: /security\s+passwords\s+min-length\s+(\d+)/i, semantic: 'password_min_length', extract: (m) => parseInt(m[1]) },
      { regex: /login\s+block-for\s+(\d+)\s+attempts\s+(\d+)/i, semantic: 'login_lockout', extract: () => true },
      { regex: /enable\s+secret/i, semantic: 'enable_secret', extract: () => true },
      { regex: /enable\s+password/i, semantic: 'enable_secret', extract: () => true },
      { regex: /logging\s+host\s+([\d.]+)/i, semantic: 'syslog_enabled', extract: () => true },
      { regex: /logging\s+trap/i, semantic: 'syslog_enabled', extract: () => true },
      { regex: /log\s+config/i, semantic: 'admin_logging', extract: () => true },
      { regex: /archive[\s\S]*?log\s+config[\s\S]*?logging\s+enable/i, semantic: 'admin_logging', extract: () => true },
      { regex: /login\s+on-failure\s+log/i, semantic: 'auth_logging', extract: () => true },
      { regex: /login\s+on-success\s+log/i, semantic: 'auth_logging', extract: () => true },
      { regex: /ntp\s+server\s+([\d.]+)/i, semantic: 'ntp_enabled', extract: () => true },
      { regex: /ntp\s+authenticate/i, semantic: 'ntp_auth', extract: () => true },
      { regex: /^no\s+service\s+pad$/m, semantic: 'unused_services', extract: () => false },
      { regex: /^no\s+cdp\s+run$/m, semantic: 'cdp_restricted', extract: () => true },
      { regex: /service\s+password-encryption/i, semantic: 'password_encryption', extract: () => true },
      { regex: /banner\s+(login|motd)/i, semantic: 'login_banner', extract: () => true },
      { regex: /access-list\s+\d+/i, semantic: 'acl_present', extract: () => true },
      { regex: /ip\s+access-list/i, semantic: 'acl_present', extract: () => true },
      { regex: /snmp-server\s+community\s+(public|private)\s/i, semantic: 'snmp_default_community', extract: () => true },
      { regex: /^no\s+snmp-server\s+community\s+(public|private)/m, semantic: 'snmp_default_community', extract: () => false },
      { regex: /ip\s+ssh\s+server\s+algorithm\s+encryption/i, semantic: 'strong_encryption', extract: () => true },
    ]
  },
  'FortiOS': {
    identifier: [
      /config\s+system\s+global/m,
      /config\s+firewall\s+policy/m,
      /config\s+system\s+interface/m,
      /set\s+hostname\s/m,
      /config\s+router/m,
      /set\s+allowaccess/m,
    ],
    patterns: [
      { regex: /set\s+admin-ssh-port\s+(\d+)/i, semantic: 'ssh_enabled', extract: () => true },
      { regex: /set\s+admin-ssh-v1\s+disable/i, semantic: 'ssh_version', extract: () => 2 },
      { regex: /set\s+admin-telnet\s+disable/i, semantic: 'telnet_enabled', extract: () => false },
      { regex: /set\s+admin-telnet\s+enable/i, semantic: 'telnet_enabled', extract: () => true },
      { regex: /set\s+admin-http\s+disable/i, semantic: 'http_management', extract: () => false },
      { regex: /set\s+admin-https\s+enable/i, semantic: 'https_management', extract: () => true },
      { regex: /set\s+allowaccess\s+(.+)/i, semantic: 'mgmt_acl', extract: () => true },
      { regex: /set\s+admintimeout\s+(\d+)/i, semantic: 'session_timeout', extract: (m) => parseInt(m[1]) * 60 },
      { regex: /set\s+min-length\s+(\d+)/i, semantic: 'password_min_length', extract: (m) => parseInt(m[1]) },
      { regex: /set\s+admin-lockout-threshold\s+(\d+)/i, semantic: 'login_lockout', extract: () => true },
      { regex: /config\s+log\s+syslogd/i, semantic: 'syslog_enabled', extract: () => true },
      { regex: /set\s+log-admin-activity\s+enable/i, semantic: 'admin_logging', extract: () => true },
      { regex: /set\s+ntpsync\s+enable/i, semantic: 'ntp_enabled', extract: () => true },
      { regex: /set\s+strong-crypto\s+enable/i, semantic: 'strong_encryption', extract: () => true },
      { regex: /set\s+pre-login-banner\s+enable/i, semantic: 'login_banner', extract: () => true },
      { regex: /config\s+firewall\s+policy/i, semantic: 'acl_present', extract: () => true },
      { regex: /config\s+user\s+local/i, semantic: 'aaa_enabled', extract: () => true },
      { regex: /set\s+password/i, semantic: 'enable_secret', extract: () => true },
      { regex: /set\s+log-auth-event\s+enable/i, semantic: 'auth_logging', extract: () => true },
    ]
  },
  'JunOS': {
    identifier: [
      /^set\s+system\s/m,
      /^set\s+interfaces\s/m,
      /^set\s+protocols\s/m,
      /^set\s+firewall\s/m,
      /^set\s+security\s/m,
      /^set\s+routing-options\s/m,
    ],
    patterns: [
      { regex: /set\s+system\s+services\s+ssh/i, semantic: 'ssh_enabled', extract: () => true },
      { regex: /set\s+system\s+services\s+ssh\s+protocol-version\s+v2/i, semantic: 'ssh_version', extract: () => 2 },
      { regex: /delete\s+system\s+services\s+telnet/i, semantic: 'telnet_enabled', extract: () => false },
      { regex: /set\s+system\s+services\s+telnet/i, semantic: 'telnet_enabled', extract: () => true },
      { regex: /set\s+system\s+services\s+web-management\s+https/i, semantic: 'https_management', extract: () => true },
      { regex: /set\s+system\s+login\s+idle-timeout\s+(\d+)/i, semantic: 'session_timeout', extract: (m) => parseInt(m[1]) * 60 },
      { regex: /set\s+system\s+syslog\s+host/i, semantic: 'syslog_enabled', extract: () => true },
      { regex: /set\s+system\s+ntp\s+server/i, semantic: 'ntp_enabled', extract: () => true },
      { regex: /set\s+firewall\s+filter/i, semantic: 'acl_present', extract: () => true },
      { regex: /set\s+system\s+login\s+password/i, semantic: 'password_min_length', extract: () => 8 },
      { regex: /set\s+system\s+login\s+message/i, semantic: 'login_banner', extract: () => true },
    ]
  }
};

// Semantic alias map for fuzzy matching of unknown vendor commands
export const semanticAliases = {
  'ssh': ['ssh', 'secure-shell', 'secure_shell', 'sshd'],
  'telnet': ['telnet', 'tel', 'cleartext-remote'],
  'timeout': ['timeout', 'idle-timeout', 'session-timeout', 'exec-timeout', 'admintimeout', 'inactivity-timer'],
  'password': ['password', 'passwd', 'secret', 'credential', 'passphrase', 'auth-pass'],
  'logging': ['logging', 'syslog', 'log', 'audit', 'audit-log', 'event-log'],
  'ntp': ['ntp', 'time-server', 'clock-server', 'time-sync', 'ntpd'],
  'aaa': ['aaa', 'authentication', 'authorization', 'accounting', 'radius', 'tacacs'],
  'acl': ['acl', 'access-list', 'access-control', 'filter', 'firewall', 'policy', 'rule'],
  'snmp': ['snmp', 'community', 'snmpd'],
  'banner': ['banner', 'motd', 'login-message', 'pre-login', 'warning-message'],
  'encryption': ['encryption', 'cipher', 'crypto', 'cryptographic', 'strong-crypto', 'aes', 'des', '3des'],
  'lockout': ['lockout', 'lock-out', 'block-for', 'failed-login', 'brute-force', 'lockout-threshold'],
  'cdp': ['cdp', 'lldp', 'discovery', 'neighbor-discovery'],
  'service': ['service', 'daemon', 'process', 'feature'],
  'http': ['http', 'web', 'web-management', 'webui', 'gui'],
  'https': ['https', 'ssl', 'tls', 'secure-web', 'secure-http'],
};

// Map semantic aliases to control parameters
export const aliasToParameter = {
  'ssh': 'ssh_enabled',
  'telnet': 'telnet_enabled',
  'timeout': 'session_timeout',
  'password': 'password_min_length',
  'logging': 'syslog_enabled',
  'ntp': 'ntp_enabled',
  'aaa': 'aaa_enabled',
  'acl': 'acl_present',
  'snmp': 'snmp_default_community',
  'banner': 'login_banner',
  'encryption': 'strong_encryption',
  'lockout': 'login_lockout',
  'cdp': 'cdp_restricted',
  'service': 'unused_services',
  'http': 'http_management',
  'https': 'https_management',
};
